### ISSUE TITLE
How to specify test run name?

### ISSUE THREAD

**Issue by MateuszMysliwiecEco** [katalon-studio/report-uploader#47]
Hello, I am trying to specify test run name, does anyone know what argument/parameter should I pass?

I tried TEST_RUN_TITLE but it did not work, test run continues to be 'Untitled test run #'

![Image](https://github.com/user-attachments/assets/2eede584-2e70-4d34-8c79-d71d15795daa)

```
upload-report:
    runs-on: ubuntu-latest
    needs: run-tests
    if: always() && inputs.uploadReport == true
    steps:
      - name: Download Test Reports
        uses: actions/download-artifact@v4
        with:
          name: katalon-test-reports
          path: Reports/

      - name: Upload Report to Katalon TestOps
        uses: katalon-studio/report-uploader@v0.0.8
        env:
          PASSWORD: ${{ secrets.KATALON_API_KEY }}  # Store this as a secret
          PROJECT_ID: xxxx
          TYPE: katalon
          REPORT_PATH: Reports/
          TEST_RUN_TITLE: "Sample test run here!"
```
